ttsx/apps/cart/urls.py
from django.conf.urls import url

from apps.cart import views

urlpatterns = [
    url(r'^add$', views.AddCartView.as_view(), name='add'),
    url(r'^update$', views.UpdateCartView.as_view(), name='update'),
    url(r'^delete', views.DeleteCartView.as_view(), name='delete'),
    url(r'^$', views.CartInfoView.as_view(), name='info'),
]

ttsx/apps/goods/urls.py
from django.conf.urls import url

from apps.goods import views

urlpatterns = [
    url(r'^index$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)$', views.ListView.as_view(), name='list'),
]

ttsx/apps/orders/urls.py
from django.conf.urls import url

from apps.orders import views

urlpatterns = [
    url(r'^place$', views.PlaceOrderView.as_view(), name='place')
]

ttsx/apps/users/urls.py
from django.conf.urls import url

from apps.users import views

urlpatterns = [
    # url(r'^register$', views.register),
    # url(r'^register$', views.RegisterView.as_view),
    # 因为Django 的URL 解析器将请求和关联的参数发送给一个可调用的函数而不是一个类
    # 所以基于类的视图有一个as_view() 类方法用来作为类的可调用入口。
    # 该as_view 入口点创建类的一个实例并调用dispatch() 方法。
    # dispatch 查看请求是GET 还是POST 等等，并将请求转发给相应的方法
    url(r'^register$', views.RegisterView.as_view(), name='register'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^active/(.+)$', views.ActivateView.as_view(), name='active'),
    url(r'^address$', views.AddressView.as_view(), name='address'),
    url(r'^userinfo$', views.UserInfoView.as_view(), name='userinfo'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import tinymce.urls
import haystack.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^', include('goods.urls', namespace='goods')),
    url(r'^tinymce/', include(tinymce.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^search/', include(haystack.urls)),
]

ttsx/apps/cart/models.py
from django.db import models

# Create your models here.

ttsx/apps/cart/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.views.generic import View
from django_redis import get_redis_connection

from goods.models import GoodsSKU


# 删除购物车数据
class DeleteCartView(View):
    def post(self, request):
        # 获取参数
        sku_id = request.POST.get('sku_id')
        # 校验参数
        if not sku_id:
            return JsonResponse({'code': 1, 'message': '参数错误'})
        # 判断是否登录
        if request.user.is_authenticated():
            # 登录就从redis中删除数据
            redis_con = get_redis_connection('default')
            # 删除sku_id对应的商品,如果存在就会删除,如果不存在,redis自动忽略
            redis_con.hdel('cart_%s' % request.user.id, sku_id)

            return JsonResponse({'code': 0, 'message': '删除成功'})
        else:
            # 未登录,就从cookie中删除
            cart_json = request.COOKIES.get('cart')
            # 判断是否有购物车cookie
            if cart_json:
                cart_dict = json.loads(cart_json)
                # 判断sku_id 对应的商品是否存在
                if sku_id in cart_dict:
                    del cart_dict[sku_id]

                    response = JsonResponse({'code': 0, 'message': '删除成功'})
                    response.set_cookie('cart', json.dumps(cart_dict))
                    return response
                return JsonResponse({'code': 6, 'message': '商品已删除'})


# 修改购物车信息
class UpdateCartView(View):
    def post(self, request):
        # 获取参数sku_id和count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        print(sku_id, count)

        # 校验参数
        if not all([sku_id, count]):
            return JsonResponse({'code': 1, 'message': '参数不完整'})
        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'message': '商品不存在'})
        # count是否为整数
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'code': 3, 'message': '商品数量有误'})
        # 判断库存
        if count > sku.stock:
            return JsonResponse({'code': 4, 'message': '库存不足'})
        # 判断用户是否登录
        if request.user.is_authenticated():
            # 登录状态,将数据存到redis中
            redis_con = get_redis_connection('default')
            redis_con.hset('cart_%s' % request.user.id, sku_id, count)
            return JsonResponse({'code': 0, 'message': '更新购物车成功'})
        else:  # 用户未登录
            # 存到cookie
            cart_json = request.COOKIES.get('cart')
            if cart_json:
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = dict()
            cart_dict[sku_id] = count
            new_cart_json = json.dumps(cart_dict)
            response = JsonResponse({'code': 0, 'message': '更新购物车成功'})
            response.set_cookie('cart', new_cart_json)
            return response


# 显示购物车页面
class CartInfoView(View):
    def get(self, request):
        '''提供购物车页面'''
        # 判断用户是否登录,如果登录,数据来自redis
        # 如果未登录,数据来自cookie
        if request.user.is_authenticated():
            # 创建redis链接
            redis_con = get_redis_connection('default')
            # 获取redis中购物车数据
            cart_dict = redis_con.hgetall('cart_%s' % request.user.id)
        else:  # 用户未登录
            # cookie中查询购物车信息,结果为json字符串
            cart_json = request.COOKIES.get('cart')
            if cart_json:
                # 将json字符串转成json字典
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = dict()

        # 需要商品sku和购物车商品数据
        # 先定义一个列表,存放sku
        skus = list()
        # 商品总价格
        total_amount = 0
        # 商品总数量
        total_count = 0
        # 获取sku_id和count
        for sku_id, count in cart_dict.items():
            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                # 商品不存在就继续遍历
                continue

            # count 装成数字类型
            count = int(count)
            # 一类商品的价格
            amount = sku.price * count
            # 将需要展示的数据保存到对象中,动态生成属性
            sku.amount = amount
            sku.count = count

            # 生成sku列表,此时的sku中有amount和count属性
            skus.append(sku)

            total_amount += amount
            total_count += count
            print(total_count, total_amount)

        # 构造上下文
        context = {
            'skus': skus,
            'total_amount': total_amount,
            'total_count': total_count
        }

        return render(request, 'cart.html', context)

        # def post(self, request):
        #     # 获取参数sku_id和count
        #     sku_id = request.POST.get('sku_id')
        #     count = request.POST.get('count')
        #     print(sku_id,count)
        #
        #     # 校验参数
        #     if not all([sku_id, count]):
        #         return JsonResponse({'code':1, 'message':'参数不完整'})
        #     # 判断商品是否存在
        #     try:
        #         sku = GoodsSKU.objects.get(id=sku_id)
        #     except GoodsSKU.DoesNotExist:
        #         return JsonResponse({'code':2, 'message':'商品不存在'})
        #     # count是否为整数
        #     try:
        #         count = int(count)
        #     except Exception:
        #         return JsonResponse({'code':3, 'message':'商品数量有误'})
        #     # 判断库存
        #     if count > sku.stock:
        #         return JsonResponse({'code':4, 'message':'库存不足'})
        #     # 判断用户是否登录
        #     if request.user.is_authenticated():
        #         # 登录状态,将数据存到redis中
        #         redis_con = get_redis_connection('default')
        #         redis_con.hset('cart_%s' % request.user.id, sku_id, count)
        #         return JsonResponse({'code':0, 'message':'更新购物车成功'})
        #     else:  # 用户未登录
        #         # 存到cookie
        #         cart_json = request.COOKIES.get('cart')
        #         if cart_json:
        #             cart_dict = json.loads(cart_json)
        #         else:
        #             cart_dict = dict()
        #         cart_dict[sku_id] = count
        #         new_cart_json = json.dumps(cart_dict)
        #         response = JsonResponse({'code':0, 'message':'更新购物车成功'})
        #         response.set_cookie('cart',new_cart_json)
        #         return response


# 添加商品进购物车
class AddCartView(View):
    """添加到购物车"""

    def post(self, request):

        # 接收数据：user_id，sku_id，count
        # 前端通过ajax发送post请求,并带有数据
        sku_id = request.POST.get('sku_id')
        print(sku_id)
        print(type(sku_id))
        count = request.POST.get('count')
        print(count)

        # 校验参数all()
        if not all([sku_id, count]):
            # code表示状态码,和前端商量决定
            return JsonResponse({'code': 1, 'message': '参数不完整'})

        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)

        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'message': '此商品不存在'})

        # 判断count是否是整数
        try:
            count = int(count)

        except Exception:
            return JsonResponse({'code': 3, 'message': '数量错误'})

        # 判断库存
        if count > sku.stock:
            return JsonResponse({'code': 4, 'message': '库存不足'})
        print('denglu')
        # 判断用户是否登陆
        if request.user.is_authenticated():
            # 只有在用户登录之后才有用户的id
            user_id = request.user.id

            # 操作redis数据库存储商品到购物车
            # 链接redis数据库
            redis_con = get_redis_connection('default')
            # 判断要添加进购物车的商品是否存在,如果不存在,返回None,存在返回sku_id对应的数量
            # hgetall(key)--->{field1:value1,field2:value2,...}
            # hget(key, field)--->field对应的value
            origin_count = redis_con.hget('cart_%s' % user_id, sku_id)

            print(origin_count)

            if origin_count:
                # 商品存在就将数量累加
                count += int(origin_count)  # origin_count为bytes类型
                print(count)
            # 购物车中此商品存在与否,最后都将数量保存
            # hash类型存储,key为cart_user_id, 属性为sku_id, 属性值为count
            redis_con.hset('cart_%s' % user_id, sku_id, count)

            # 为了配合前端展示商品在购物车的总数，后台需要查询购物车的所有的商品的数量求
            cart_num = 0
            # 获得user_id对应下的所有购物车中的商品
            cart_dict = redis_con.hgetall('cart_%s' % user_id)
            # cart_dict.values()--->获取字典中的value,返回列表
            for val in cart_dict.values():
                print(val)
                cart_num += int(val)
            print(cart_num)
            # json方式响应添加购物车结果
            return JsonResponse({'code': 0, 'message': '加入购物车成功', 'cart_num': cart_num})

        else:  # 用户未登录,将数据存在cookie中
            # return JsonResponse({'code': 5, 'message': '用户未登录'})
            # 如果用户未登录，就保存购物车数据到cookie中,cart:{sku_id1:10,sku_id2:20,...}
            # 先从cookie的购物车信息中，获取当前商品的购物车记录,即json字符串购物车数据
            # cart是在cookie中存数据的key
            cart_json = request.COOKIES.get('cart')  # --->json字符串'{'':'','':'',...}'

            print(cart_json)

            # 判断购物车cookie数据是否存在，有可能用户从来没有操作过购物车
            if cart_json:
                # cookie中已经有购物车数据,将json字符串转换为json字典类型
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = dict()  # 设置空字典,备用

            print(cart_dict)

            # 判断要加入购物车的商品是否存在
            if sku_id in cart_dict:  # sku_id
                count += int(cart_dict[sku_id])
            # 将数据存入
            cart_dict[sku_id] = count
            # 将json字典装换成json字符串
            new_cart_json = json.dumps(cart_dict)
            # 计算购物车数据
            cart_num = 0
            for val in cart_dict.values():
                cart_num += int(val)

            response = JsonResponse({'code': 0, 'message': '加入购物车成功', 'cart_num': cart_num})

            # 将数据存入cookie中
            response.set_cookie('cart', new_cart_json)

            print(response, cart_num)

            return response

ttsx/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {% block title %}{% endblock title %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock topfiles %}

</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_info fl" style="display: block">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'users:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl" style="display: block">
                        <a href="{% url 'users:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'users:register' %}">注册</a>
				    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:userinfo' %}">用户中心</a>
					<span>|</span>

                    <a href="{% url 'cart:info' %}">
                        {% if user.is_authenticated %}
                        我的购物车
                        {% else %}
                        购物车
                        {% endif %}
                    </a>


					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% block middle %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">
                {% if user.is_authenticated %}
                我的购物车
                {% else %}
                购物车
                {% endif %}
            </a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
{% endblock middle %}
	{% block body %}

	{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block footer %}{% endblock footer %}
{% block endscript %}

{% endblock endscript %}
</body>
</html>

ttsx/templates/detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    天天生鲜-商品详情
{% endblock title %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in categorys %}
                        {#                        <li><a href="#model0{{ forloop.counter }}" class="{{ category.logo }}">{{ category.name }}</a></li>#}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="/">全部分类</a>
        <span>></span>
        <a href="{% url 'goods:list' sku.category.id 1 %}?sort=default">{{ sku.category.name }}</a>
        {#		<a href="#">{{ sku.category.name }}</a>#}
        <span>></span>
        <a href="{% url 'goods:detail' sku.id %}">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

        <form method="post" action="{% url 'orders:place' %}">

        {% csrf_token %}
{#        技巧:设置一个隐藏input标签,来收集form表单中sku_id的值#}
        <input type="hidden" name="sku_ids" value="{{ sku.id }}">

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.title }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unit }}</span>
            </div>
            {% if other_skus %}
                <div>
                    <p>其他规格:</p>
                    <ul>
                        {% for other_sku in other_skus %}
                            <li>
                                <a href="{% url 'goods:detail' other_sku.id %}">{{ other_sku.price }}/{{ other_sku.unit }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" name="count" value="1" id="num_show">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>
                </div>
            </div>
            <div class="total">总价：<em>{{ sku.price }}元</em></div>
            <div class="operate_btn">
                {% if user.is_authenticated %}
                <input type="submit" class="buy_btn" id="buy_btn" value="立即购买">
                {% else %}
                <a href="{% url 'users:login' %}?next={{ request.path }}" class="buy_btn" id="buy_btn">立即购买</a>
                {% endif %}
{#                <input type="submit" class="buy_btn" id="buy_btn" value="立即购买">#}
{#                <input type="submit" class="buy_btn" id="buy_btn" value="立即购买">#}
                <a href="javascript:;" class="add_cart" id="add_cart" sku_id="{{ sku.id }}">加入购物车</a>
            </div>
        </div>
        </form>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}"><img
                                    src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li id="tag_detail" class="active">商品介绍</li>
                <li id="tag_comment">评论</li>
            </ul>

            <div class="tab_content" id="tab_detail">
                <dl>
                    <dt>商品详情：</dt>
                    {#                    desc|safe 关闭转义,告诉模板这个变量是安全的,可以执行#}
                    <dd>{{ sku.goods.desc|safe }}</dd>
                </dl>
            </div>

        </div>
    </div>
{% endblock body %}

{% block footer %}
    <div class="add_jump"></div>
{% endblock footer %}

{% block endscript %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $("#tag_detail").click(function () {
            $("#tag_comment").removeClass("active");
            $(this).addClass("active");
            $("#tab_comment").hide();
            $("#tab_detail").show();
        });

        $("#tag_comment").click(function () {
            $("#tag_detail").removeClass("active");
            $(this).addClass("active");
            $("#tab_detail").hide();
            $("#tab_comment").show();
        });

        $("#buy_btn").click(function () {
            var count = $("#num_show").val();
            window.location.href = '/order/commit?g={{goods.id}}@' + count;
        });

        // 点击加入购物车
        $('#add_cart').click(function () {
            // 将商品的id 和 数量发送给后端视图，保存到购物车数据中
            var req_data = {
{#                name: "detail",#}
                sku_id: $('#add_cart').attr("sku_id"),
                count: $("#num_show").val(),
                csrfmiddlewaretoken: "{{ csrf_token }}"
            };

            // 使用ajax向后端发送数据
            $.post('/cart/add', req_data, function (response_data) {
                if (0 == response_data.code) {
                    var $add_x = $('#add_cart').offset().top;
                    var $add_y = $('#add_cart').offset().left;
                    var $to_x = $('#show_count').offset().top;
                    var $to_y = $('#show_count').offset().left;
                    $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'});
                    // 添加购物车成功的
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                $('#show_count').html(response_data.cart_num);
                            });
                        });
                } else {
                    // 添加购物车失败
                    alert(response_data.message);
                }
            });
        });
        $(".add").click(function () {
            var num_show = $('#num_show').val();
            num_show = parseInt(num_show);
            num_show += 1;
            {#			alert(num_show);#}
            $("#num_show").val(num_show);
            var price = $(".show_pirze>em").html();
            price = parseFloat(price);
            var total = price * num_show;
            $(".total>em").html(total.toFixed(2));
        });
        $(".minus").click(function () {
            var num_show = $("#num_show").val();
            num_show = parseInt(num_show);
            num_show -= 1;
            if (num_show < 1) {
                num_show = 1;
            }
            $("#num_show").val(num_show);
            var price = $(".show_pirze>em").html();
            price = parseFloat(price);
            var total = price * num_show;
            $(".total>em").html(total.toFixed(2));
        });
    </script>

{% endblock endscript %}

ttsx/templates/static_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {% block title %}{% endblock title %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock topfiles %}

</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                    <div class="login_btn fl" style="display: block">
                        <a href="{% url 'users:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'users:register' %}">注册</a>
				    </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:userinfo' %}">用户中心</a>
					<span>|</span>
					<a href="#">我的购物车</a>
					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% block middle %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
{% endblock middle %}
	{% block body %}

	{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% block endscript %}

{% endblock endscript %}
</body>
</html>

ttsx/templates/user_center_site.html
{% extends 'userbase.html' %}

{% load staticfiles %}



{% block body %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:userinfo' %}" >· 个人信息</a></li>
				<li><a href="#">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if address %}
                            <dd>
                                {{ address.consignee_add }} （{{ address.consignee }} 收） {{ address.consignee_tel }}
                            </dd>
                        {% endif %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="recv_name">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="recv_addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zipcode">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="recv_tel">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
    </div>
{% endblock body %}


